### ISSUE TITLE
MVPリリース　提出用issue

### ISSUE THREAD

**Issue by nakajima-takeshi** [nakajima-takeshi/stockmate#110]
# MVPリリース　提出
サービス名：Stock Mate
サービスURL：https://stockmate.dev/

### ユーザー登録・ログイン
  - [ ] ユーザー名,パスワード
  - [x] LINE連携ログイン  **入力必須**
  - [x] LINEに友達追加

### 解説
- ユーザー登録機能はLINE連携ログインと友達追加された際のLINEへのメッセージのみ実装し、通常のユーザー登録やログイン機能は実装していません。理由としては、本アプリはLINEへの通知が必須となっており、LINE連携ログインを実行すれば同時にユーザー登録と友達追加が実行されるためです。

## 日用品の登録機能
  - [x] ジャンル選択(シャンプー、ティッシュBOXなど):選択したジャンルごとにフォーマット用意し、そのページに遷移
  - [x] 商品名入力
  - [x] 内包量
    - [x] フォーマットごとに単位が変わる。 **入力必須**
  - [x] １日の使用回数  **入力必須**
  - [x] フリーメモ
    - [x] 空欄の際は未登録と詳細ページに表示されます。
    - [x] 内容はLINE通知のmessageに一緒に通知されます。

### 解説
- 概ねREADME通りの実装ができました。ジャンル選択においてフォーマットが変わるのではなく、セレクトボックスで選択したジャンルによって単位がmgとmLで変わるようにTurboで実装しました。
また、選択肢に「その他」を設計し、その他を選択した場合、デフォルトで通知予定日が2週間後になるように設定しました。

## 登録した日用品一覧の表示、基本的CRUD機能
- [x] ユーザーはトップページに上記登録内容が表示されます。
- [x] 通知予定日時が一覧、詳細画面に確認できます。
  - [x] 通知予定日時をユーザーが任意で変更できます。

### 解説
- ログイン後のトップページ（マイページ）に登録内容が一覧で表示されます。画像をクリックすると詳細ページに遷移します。（本リリースでは各カテゴリーに剃ったアイコンを設定します。）
一覧ページ、詳細ページには以下の３つのボタンが用意されています。
  - 通知予定日編集ボタン（時計のアイコン）
  - 日用品登録内容編集ボタン（ペンのアイコン）
  - 登録内容削除ボタン（バケツのアイコン）
通知予定日編集ボタンを選択すると編集ページがモーダルで表示され、変更内容がTurboで速やかに切り替わります。
日用品登録内容編集ボタンを選択すると、編集ページに遷移します。変更時、内包量と一日の使用回数の２箇所が変更された場合にのみ次回通知日の再計算が行われ、商品名やメモのみの変更の際は再計算が行われません。そうすることで、通知予定日を自身で設定した場合でも上書きされてしまうことを防ぎます。

## 通知機能
- [x] LINEへの通知
  - [x] 通知を受け取れます。

### 解説
- 本サービスの肝となる機能で、問題なく実装できています。一日に１回、昼12時に登録内容を検証し、通知予定日が今日となっている通知をユーザーのアプリへ送信します。

## READMEレビュー時から変更した機能
- 削除した機能
  - ユーザー登録
  - LINE友達追加QRコード
- 追加した機能
  - 通知予定日の編集ページのモーダル実装
### 解説
当初は通知予定日の編集ページを作成したのですが、以下の理由でモーダルで実装しました。
１）編集ページがスカスカになってしまい、見栄えが悪いと感じたため
２）ページ遷移が少ない方がユーザー体験が向上すると考えたため

また、MVP提出に伴って一部仕様をMVP判定をしてもらうために変更しています。
- 通知予定日は明日以降の日付しか登録できない設定になっていますが、現在は今日の日付で登録できるように変更しています。
- 通知は一日１回、PM12時に送信するようになっているのですが、現在は10分ごとに判定し通知が来るようにしてあります。

いずれもLGTM判定をいただいた後に戻す予定です。
---
## サービスイメージがわかるようなスクリーンショット等
- 一覧ページ
![image](https://github.com/user-attachments/assets/b6ca85b2-c7a2-4747-a952-3a8df97fd34d)
- スマホ画面レイアウト
![image](https://github.com/user-attachments/assets/13d28720-1da5-4908-98f8-57ec9688c81c)

- 新規作成・編集ページ
![image](https://github.com/user-attachments/assets/b03a2ce3-a5f7-45d1-89e3-7b9f891e5b80)
- 詳細ページ
![image](https://github.com/user-attachments/assets/a377d24e-e1c9-40e1-a52b-09a7a0ef349d)
- スマホ画面レイアウト
![image](https://github.com/user-attachments/assets/31c354d6-911c-4686-b7d9-e454486b3149)
- 通知予定日編集モーダル
![image](https://github.com/user-attachments/assets/573a0968-ce4e-4bc6-83a7-ec4315b55bc1)

**Comment by nakajima-takeshi** [comment]
２回目の提出です。
LINE公式でのプロバイダ内でLINEログイン設定を本番環境用に切り替え忘れていたのがエラーの原因でした。申し訳ありません。

切り替えて動作確認をしましたので、改めてよろしくお願いします。

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです〜！
引き続き本リリースに向けて開発頑張ってください！！

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
