### ISSUE TITLE
issueベースの開発　レビュー依頼

### ISSUE THREAD

**Issue by nakajima-takeshi** [nakajima-takeshi/stockmate#4]
１回目の提出です。

READMEについて、一部変更があります。
本リリース後の実装機能を、検索機能、カレンダー機能から、LINEリッチメニューに変更しました。

## 理由
サービスの軸を「全てのサービスをLINE上で完結させる」ということに一本化したいと思ったため、便利だからと、色々とサービスを設けるより、よりシンプルなアプリ設計にしたいと思いました。

### 本リリース実装
- LINEリッチメニュー機能
  - LINE上のメニューから、現在登録されている内容の確認や変更、更新が行えます。

開始日時を11/18としていますが、レビューLGTMがもらえ次第、開発を始めます。
どうぞよろしくお願いします。

## Webアプリの概要
READMEをご確認ください。

## 1週間辺りの開発に向けられる時間
- 1週間あたり：30~40時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

## ProjectsのURL
https://github.com/users/nakajima-takeshi/projects/1/views/1

## MVPリリース
- [x] rails new
- [x] Herokuにデプロイ
- [x] トップページ
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 日用品の登録機能
- [x] LINEログイン機能
- [x] LINE友達登録機能
- [x] LINEプッシュ通知機能

## MVP後
- [x] 使い方
- [x] 利用規約・プライバシーポリシー
- LINEリッチメニュー機能
  - LINE上のメニューから、現在登録されている内容の確認や変更、更新が行えます。

## MVPレビュー依頼予定日
予定日：2024年 12月 29日

**Comment by nakajima-takeshi** [comment]
ご指摘ありがとうございます。こちらのカリキュラムの確認不足でした。
改めてissueの内容、実装の流れなどを細分化および見直しを行いました。

## 変更箇所
- パスワードリセット、利用規約・プライバシーポリシーをMVP後にしました。
- LINE機能実装ですが、複雑なエラーが確実に予想されるので、２週間とストーリーポイント以上に長く見積もりました。


２回目の提出になります。どうぞよろしくお願いします。

---
## Webアプリの概要
READMEをご確認ください。

## 1週間辺りの開発に向けられる時間
- 1週間あたり：20~30時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

## ProjectsのURL
https://github.com/users/nakajima-takeshi/projects/1/views/1

## MVPリリース
- [x] rails new
- [x] Herokuにデプロイ
- [x] トップページ
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 日用品の登録機能
- [x] LINEログイン機能
- [x] LINE友達登録機能
- [x] LINEプッシュ通知機能

## MVP後
- [x] 使い方
- [x] 利用規約・プライバシーポリシー
- LINEリッチメニュー機能
  - LINE上のメニューから、現在登録されている内容の確認や変更、更新が行えます。

## MVPレビュー依頼予定日
予定日：2024年 12月 22日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
